#!/bin/bash
/system/install supervisor
cat <<\EOF > /etc/supervisor/conf.d/radio2serial.conf
[program:radio2serial]
command=/do/radio2serial/check
autostart=true
autorestart=true
stdout_logfile=/var/log/radio2serial.log
redirect_stderr=true
logfile_maxbytes=10MB
logfile_backups=0
EOF
supervisorctl reread
supervisorctl update
