#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
		/show/messagebox "$0"
		/show/info "[beta] [radio] [433Mhz] [socket] [warning]"
		/show/usageDescription "Kill radio socket"
		/show/usage "$0"
		exit 1
else
	port=$(cat /user/config/radio2serial/port)
	fuser -k $port/tcp
fi