#!/bin/bash
/show/description "radio Status"
/show/listecho  "PRESS [CTRL-C] to quit" $WARN
/show/listecho "Supervisor status" $OK
supervisorctl status radio
/show/description "radio log" $OK
tail -f /var/log/radio2serial.log

