#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
		/show/messagebox "$0"
		/show/info "[beta] [radio] [433Mhz] [log] [supervisor]"
		/show/usageDescription "Display radio2serial log"
		/show/usage "$0"
		exit 1
else
	/show/description "radio Status"
	/show/listecho  "PRESS [CTRL-C] to quit" $WARN
	/show/listecho "Supervisor status" $OK
	supervisorctl status radio
	/show/description "radio log" $OK
	tail -f /var/log/radio2serial.log
fi