#!/bin/bash

string=$(echo $1 | iconv -f utf-8 -t us-ascii//TRANSLIT)
len=${#string}
sleep 1
while [ $len -ge 59 ] ;
do
   #lets split this up so that its a maximum of 99 characters
    tmp=${string:0:59}
    string=${string:59}

    echo $string
    sleep 1

    len=${#string}
    /do/radio2serial/send "/radio/text/$tmp"
    sleep 1
done

/do/radio2serial/send "/radio/text/$string"

